# Generated by Django 5.0.3 on 2024-04-01 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
